import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import { Providers } from '@/components/shared/Provider'
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from '@/components/ui/toaster'
import NextTopLoader from 'nextjs-toploader'
import { GlobalProvider } from '@/context/globalProvider'
const nunito = Nunito({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <GlobalProvider>
          <ClerkProvider>
            <NextTopLoader
              height={2}
              color="red"
              easing="cubic-bezier(.0.53,0.21,0,.0.1)"
              showSpinner={false}
            />
            <Providers>{children}</Providers>
            <Toaster />
          </ClerkProvider>
        </GlobalProvider>
      </body>
    </html>
  )
}
